# Generated by Django 3.0.4 on 2020-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="telefon"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "čekatel"),
                    ("active", "aktivní"),
                    ("disabled", "blokován"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
