# Generated by Django 3.0.4 on 2020-03-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200319_2146"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "uživatel",
                "verbose_name_plural": "uživatelé",
            },
        ),
    ]
