# Generated by Django 3.0.4 on 2020-03-24 22:49

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200321_1858"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "uživatel",
                "verbose_name_plural": "uživatelé",
            },
        ),
        migrations.AlterModelManagers(
            name="user", managers=[("objects", users.models.UserManager()),],
        ),
        migrations.RemoveField(model_name="user", name="username",),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
