stages:
  - build

image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG_APP: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - docker:19.03.1-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG_APP .
    - docker push $IMAGE_TAG_APP
