# Generated by Django 3.0.4 on 2020-03-22 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200322_2303"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Location",
            ),
            preserve_default=False,
        ),
    ]
