# Generated by Django 3.0.4 on 2020-03-19 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="název")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "aktivní"), ("disabled", "pozastavena")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="popis"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="adresa"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="telefon")),
            ],
            options={"ordering": ["region", "name"],},
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="název")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "k dispozici"), ("disabled", "blokován")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "limit",
                    models.FloatField(
                        blank=True, null=True, verbose_name="limit výdeje"
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="perioda výdeje"
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="název")),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="popis"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "aktivní"), ("disabled", "pozastaven")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="RegionAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.Region"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="region",
            name="admins",
            field=models.ManyToManyField(
                through="main.RegionAdmin", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="MaterialRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="množství")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="datum")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("received", "přijetí"),
                            ("returned", "vrácení"),
                            ("dispensed", "výdej"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="operace",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Location"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Material"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Region"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["date"],},
        ),
        migrations.AddField(
            model_name="material",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.Region"
            ),
        ),
        migrations.CreateModel(
            name="LocationStaff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "čekatel"),
                            ("admin", "správce"),
                            ("volunteer", "dobrovolník"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.Location"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.Region"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="staff",
            field=models.ManyToManyField(
                through="main.LocationStaff", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Dispensed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="množství")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="upraveno"),
                ),
                (
                    "id_card_no",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="číslo průkazu"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Location"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Material"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Region"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["created"],},
        ),
    ]
