# Generated by Django 3.0.4 on 2020-03-19 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispensed",
            options={
                "ordering": ["created"],
                "verbose_name": "Výdej",
                "verbose_name_plural": "Výdeje",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["region", "name"],
                "verbose_name": "Lokalita",
                "verbose_name_plural": "Lokality",
            },
        ),
        migrations.AlterModelOptions(
            name="locationstaff",
            options={
                "ordering": ["location", "user"],
                "verbose_name": "Personál lokality",
                "verbose_name_plural": "Personál lokality",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["name"],
                "verbose_name": "Materiál",
                "verbose_name_plural": "Materiály",
            },
        ),
        migrations.AlterModelOptions(
            name="materialrecord",
            options={
                "ordering": ["date"],
                "verbose_name": "Záznam materiálu",
                "verbose_name_plural": "Záznamy materiálů",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ["name"],
                "verbose_name": "Oblast",
                "verbose_name_plural": "Oblasti",
            },
        ),
        migrations.AlterField(
            model_name="dispensed",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Location",
                verbose_name="lokalita",
            ),
        ),
        migrations.AlterField(
            model_name="dispensed",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Material",
                verbose_name="materiál",
            ),
        ),
        migrations.AlterField(
            model_name="dispensed",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Region",
                verbose_name="oblast",
            ),
        ),
        migrations.AlterField(
            model_name="dispensed",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="uživatel",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="telefon"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Region",
                verbose_name="oblast",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="staff",
            field=models.ManyToManyField(
                through="main.LocationStaff",
                to=settings.AUTH_USER_MODEL,
                verbose_name="personál",
            ),
        ),
        migrations.AlterField(
            model_name="locationstaff",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Location",
                verbose_name="lokalita",
            ),
        ),
        migrations.AlterField(
            model_name="locationstaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="uživatel",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Region",
                verbose_name="oblast",
            ),
        ),
        migrations.AlterField(
            model_name="materialrecord",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Location",
                verbose_name="lokalita",
            ),
        ),
        migrations.AlterField(
            model_name="materialrecord",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Material",
                verbose_name="materiál",
            ),
        ),
        migrations.AlterField(
            model_name="materialrecord",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Region",
                verbose_name="oblast",
            ),
        ),
        migrations.AlterField(
            model_name="materialrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="uživatel",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="admins",
            field=models.ManyToManyField(
                through="main.RegionAdmin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uživatel",
            ),
        ),
        migrations.AlterField(
            model_name="regionadmin",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Region",
                verbose_name="oblast",
            ),
        ),
        migrations.AlterField(
            model_name="regionadmin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="uživatel",
            ),
        ),
    ]
