# Generated by Django 3.0.4 on 2020-03-21 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_auto_20200319_2222"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispensed",
            options={
                "ordering": ["-created"],
                "verbose_name": "Výdej",
                "verbose_name_plural": "Výdeje",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["name", "region"],
                "verbose_name": "Materiál",
                "verbose_name_plural": "Materiály",
            },
        ),
        migrations.AlterModelOptions(
            name="materialrecord",
            options={
                "ordering": ["-date"],
                "verbose_name": "Záznam pohybu materiálu",
                "verbose_name_plural": "Záznamy pohybů materiálů",
            },
        ),
        migrations.AlterModelOptions(
            name="regionadmin",
            options={
                "verbose_name": "Správce oblasti",
                "verbose_name_plural": "Správci oblasti",
            },
        ),
        migrations.AddField(
            model_name="materialrecord",
            name="dispensed",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Dispensed",
            ),
        ),
        migrations.AlterField(
            model_name="locationstaff",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "čekatel"),
                    ("admin", "koordinátor"),
                    ("volunteer", "dobrovolník"),
                ],
                default="pending",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="admins",
            field=models.ManyToManyField(
                through="main.RegionAdmin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="správce",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="status",
            field=models.CharField(
                choices=[("active", "aktivní"), ("disabled", "pozastaveno")],
                db_index=True,
                default="active",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
