# Generated by Django 3.0.4 on 2020-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20200321_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispensed",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="množství"),
        ),
    ]
