# Generated by Django 3.0.4 on 2020-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20200321_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=1000, unique=True, verbose_name="název"),
        ),
    ]
