# Generated by Django 3.0.4 on 2020-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_blacklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklist",
            name="id_card_no",
            field=models.BigIntegerField(db_index=True, verbose_name="číslo průkazu"),
        ),
        migrations.AlterField(
            model_name="dispensed",
            name="id_card_no",
            field=models.BigIntegerField(db_index=True, verbose_name="číslo průkazu"),
        ),
    ]
