# Generated by Django 3.0.4 on 2020-03-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20200324_1519"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["id"],
                "verbose_name": "Lokalita",
                "verbose_name_plural": "Lokality",
            },
        ),
        migrations.RemoveField(model_name="materialrecord", name="dispensed",),
    ]
