# Generated by Django 3.0.4 on 2020-03-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_auto_20200324_2148"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="region_name",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="název regionu"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="region_name",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="název regionu"
            ),
        ),
        migrations.AlterField(
            model_name="dispensed",
            name="id_card_no",
            field=models.BigIntegerField(db_index=True, verbose_name="číslo dokladu"),
        ),
        migrations.AlterField(
            model_name="location",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Markdown syntaxe. Nadpisy nejsou povolené a nezobrazí se na webu!",
                null=True,
                verbose_name="popis",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Markdown syntaxe. Nadpisy nejsou povolené a nezobrazí se na webu!",
                null=True,
                verbose_name="popis",
            ),
        ),
    ]
