# Generated by Django 3.0.4 on 2020-03-26 22:14

from django.db import migrations


def denormalize_region_names(apps, schema_editor):
    Region = apps.get_model("main", "Region")
    for region in Region.objects.all():
        region.location_set.all().update(region_name=region.name)
        region.material_set.all().update(region_name=region.name)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20200326_2313"),
    ]

    operations = [
        migrations.RunPython(
            denormalize_region_names, reverse_code=migrations.RunPython.noop
        ),
    ]
